# Generated by Django 5.0 on 2023-12-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('writer', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=55)),
                ('blog', models.CharField(max_length=255)),
            ],
        ),
    ]
